version: "3"
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    image: testing_app:test
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
            - "~/test/data/:/data"
    deploy:
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:
